### PR TITLE
Add data management plan

### PR DESCRIPTION
**Pull request by brinxmat**
Added data management plan

### CODE REVIEW

**Review by axthosarouris — CHANGES_REQUESTED** [review]
Bump the model version

**Review by axthosarouris — DISMISSED** [review]

**Comment by brinxmat** [comment]
> Bump the model version

I was just thinking about this, will fix

**Comment by axthosarouris** [comment]
> > Bump the model version
> 
> I was just thinking about this, will fix

:+1:

**Review by axthosarouris — APPROVED** [review]
LGTM

**Pull request merged**
